# Generated by Django 4.1.5 on 2023-03-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist_wisheditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='transition_id',
        ),
    ]
