# Generated by Django 4.1.5 on 2023-05-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_seller_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisheditems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wisheditems',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='WishedItems',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
